#
# Main application configuration file used by App Engine
#

# The name and version of the application
application: fireworks-skylight 
version: 0-3

# The App Engine runtime api specification
runtime: python
api_version: 1

# request handler directives
handlers:

# One ring to rule them all.
- url: /.*
  script: request.py

