#
# Main application configuration file used by App Engine
#

# The name and version of the application
application: fireworks-skylight 
version: 0-3

# The App Engine runtime api specification
runtime: python
api_version: 1

# request handler directives
handlers:

# Print out a list of the environment variables in text/plain
- url: /environs
  script: environs.py

# Insecure, local only, to setup a tempory sys admin for testing.
- url: /testsetup
  script: testsetup.py

# One ring to rule them all.
- url: /.*
  script: handler.py

