#
# Main application configuration file used by App Engine
#

# The name and version of the application
application: fireworks-skylight 
version: 0-1-2

# The App Engine runtime api specification
runtime: python
api_version: 1

# request handler directives
handlers:

  # Return the robots.txt file for crawler bots.
- url: /robots.txt
  script: robots.py

  # Print out a list of environment variables set by App Engine and return as
  # an http response.
- url: /environs
  script: environs.py

  # Set up for user testing
  # ON LOCAL dev_appserver ONLY !!! (security)
- url: /testsetup
  script: testsetup.py

  # All other requests are sent to request.py
- url: /.*
  script: request.py

