application: fireworks-skylight 
version: 5
runtime: python
api_version: 1

handlers:
- url: /robots.txt
  script: robots.py

- url: /users/
  script: users.py

- url: /environs
  script: environs.py

- url: /.*
  script: request.py
